addSbtPlugin("com.dwijnand"      % "sbt-dynver"         % "4.1.1")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"       % "2.4.0")
addSbtPlugin("de.heikoseeberger" % "sbt-header"         % "5.5.0")
addSbtPlugin("org.wartremover"   % "sbt-wartremover"    % "2.4.10")
addSbtPlugin("com.typesafe.sbt"  % "sbt-license-report" % "1.2.0")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"            % "2.0.1")
