addSbtPlugin("com.dwijnand"      % "sbt-dynver"         % "3.3.0")
addSbtPlugin("com.geirsson"      % "sbt-scalafmt"       % "1.5.1")
addSbtPlugin("de.heikoseeberger" % "sbt-header"         % "5.1.0")
addSbtPlugin("org.wartremover"   % "sbt-wartremover"    % "2.4.1")
addSbtPlugin("com.typesafe.sbt"  % "sbt-license-report" % "1.2.0")
addSbtPlugin("com.typesafe.sbt"  % "sbt-license-report" % "1.2.0")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"            % "1.1.1")
